# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
    - number: 1007
    - number: 1015
    - number: 58
    - number: 107

import:
  - file: JLCPCB
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/JLCPCB

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV

outputs:
  - name: basic_ibom
    comment: Interactive HTML BoM
    type: ibom
    dir: Assembly
    options:
      # https://kibot.readthedocs.io/en/master/configuration/outputs/IBoMOptions.html
      name_format: index
      dark_mode: true
      highlight_pin1: selected
      no_compression: true
      include_nets: true
      include_tracks: true
      extra_data_file: "%F.kicad_pcb"
      extra_fields: Description,LCSC
