# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
    - number: 1007
    - number: 1015
    - number: 58
    - number: 107

import:
  - file: Elecrow
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/Elecrow
  - file: ExportProject
  - file: FusionPCB
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/FusionPCB
  - file: JLCPCB
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/JLCPCB
      _KIBOT_POS_PRE_TRANSFORM: "['_kicost_rename', '_rot_footprint']"
  - file: MacroFab_XYRS
    definitions:
      _KIBOT_MPN_FIELD: ""
  - file: PCB2Blender_2_1
  - file: PCBWay
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/PCBWay
  - file: PanelDemo_4x4

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV

outputs:
  - name: basic_ibom
    comment: Interactive HTML BoM
    type: ibom
    dir: Assembly
    options:
      # https://kibot.readthedocs.io/en/master/configuration/outputs/IBoMOptions.html
      name_format: index
      dark_mode: true
      highlight_pin1: selected
      no_compression: true
      include_nets: true
      include_tracks: true
      extra_fields: Description,LCSC
