name: kibot

on:
  push:
    paths:
    - '.github/workflows/kibot.yaml'
    - '**.kicad_pcb'
    - '**.sch'
    - 'sensorstick/config.kibot.yaml'

  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        # Required - kibot config file
        config: sensorstick/config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        schema: 'sensorstick/sensorstick.kicad_sch'
        # optional - PCB design file
        board: 'sensorstick/sensorstick.kicad_pcb'
    - name: upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: kibot
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
